### ISSUE TITLE
华为mate9无法识别问题

### ISSUE THREAD

**Issue by gaojiangmin** [Simon-Leeeeeeeee/XCodeScanner#10]
在华为mate9手机上 无法扫码识别  同一手机上的微信、自带浏览器以及第三方浏览器对同一二维码都可识别。图片无法上传 只能手打了 
设备名称：HUAWEI Mate9  
手机型号：MHA-AL00
版本号：MHA-AL00C00B233
EMUI版本：5.0.1
Android版本：7.0

**Comment by Simon-Leeeeeeeee** [comment]
是否特定某个二维码不能识别？还是所有二维码都不能识别？

**Comment by Simon-Leeeeeeeee** [comment]
你好，真机测试华为mate9没出现所述问题，方便加我微信沟通吗？

**Comment by klaokai** [comment]
我测试的机型是飞利浦的I999，发现二维码填满整个识别框的时候是没有识别的，离远了之后，二维码大约占小于于识别框的1/4的样子才会识别。无法识别的问题会不会是因为二维码填满整个扫描框没有结果显示造成的误解？

**Comment by Simon-Leeeeeeeee** [comment]
@klaokai 你好，经过与楼主沟通，mate9无法识别的原因是显示二维码的显示器有问题，二维码被遮挡造成。你说的距离影响二维码识别的问题与图像帧的分辨率、二维码清晰度&复杂度有关，后期会进行优化。
