### ISSUE TITLE
1.1.7依赖有问题

### ISSUE THREAD

**Issue by 574085757** [Simon-Leeeeeeeee/XCodeScanner#18]

**Comment by Simon-Leeeeeeeee** [comment]
@574085757 具体什么问题呢？如果是无法添加依赖，请检查AndroidStudio。如果是添加后使用报错，请附上错误日志。

**Comment by djlmsm111** [comment]
1.1.7当添加依赖了以后加载是没有问题的,而且用的是zbar1.1.7,但是你的demo里边全部都是1.1.5的方法,在1.1.7的里边有好几个方法是没有了的  mCameraScanner.setSurfaceTexture(mTextureView.getSurfaceTexture());等等
这个你自己新建一个项目立马就能知道的

**Comment by Simon-Leeeeeeeee** [comment]
@574085757 @djlmsm111 经核实，1.1.7中原本的setSurfaceTexture接口被我改成了setPreviewTexture，但是更新说明中忘记提及。是我大意疏忽了，对此造成的困扰非常抱歉！稍后核实其他API改动后我会更新使用说明。感谢反馈！
