### ISSUE TITLE
关于新api和旧api的差别

### ISSUE THREAD

**Issue by OvenCroc** [Simon-Leeeeeeeee/XCodeScanner#20]
三星s7 
android版本7.0.0
用新api会慢很多,但是旧api就识别的非常的快,大兄弟给你反馈一下

**Comment by OvenCroc** [comment]
用你的demo也是一样的效果

**Comment by Simon-Leeeeeeeee** [comment]
@OvenCroc 因为两种方式获取的图像分辨率有所区别，间接影响到识别效果。后面会进行优化
